### ISSUE TITLE
com.unarin.cordova.beacon@3.3.0 does not exist

### ISSUE THREAD

**Issue by jungselius** [mbanting/meteor-reactive-ibeacons#7]
Quick fix: paste com.unarin.cordova.beacon@3.4.0 into .meteor/cordova-plugins

**Comment by jtkeyva** [comment]
+1, I'm getting this error and haven't been able to figure it out. @jungselius can you please elaborate on how you did that? I don't understand what you mean by paste ?  Thx

**Comment by jungselius** [comment]
Hi @jtkeyvaIn. In the directory .meteor u should find a file named cordova-plugins. Copy and paste com.unarin.cordova.beacon@3.4.0 into that file.

**Comment by mbanting** [comment]
Real sorry for the delay. Will try and get to this this weekend. 
Does this have anything to do with a Meteor 1.3 upgrade or did this just stop working?
